spring:
  application:
    name: reader-writer-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  batch:
    job:
      enabled: false
    initialize-schema: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        default_schema: DBO

  data:
    mongodb:
      database: tradesDB
      host: localhost
      port: 27017

  flyway:
    user: root
    password: admin05
    group: true
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/crypto'
    locations: classpath:db/migration
    schemas: crypto
    placeholders:
      schema: 'CRYPTO'
    baseline-on-migrate: true
    baseline-description: 'Base Version'
    baseline-version: 1.0.0
    table: 'FLYWAY_SCHEMA_HISTORY'



server:
  port: 8500


logging:
  level:
    root: ERROR
    com.sjtech: DEBUG
    org.springframework: INFO
    org.flywaydb: INFO


coindump:
  dir:
    incoming: 'C:\\work\\filewatch\\incoming'
    archive: 'C:\\work\\filewatch\\archive'


service:
  datasource:
    trade:
      username: root
      url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/crypto'
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource